version: '3.6'

services:
  producer:
    build:
      context: .
    volumes:
      - .:/projeto
    environment:
      - RABBITMQ_HOST=rabbitmqServer
    networks:
      - rabbit-network
    depends_on:
      - rabbit
  receiver:
    build:
      context: .
    command: python3 -u receiver.py
    volumes:
      - .:/projeto
    environment:
      - RABBITMQ_HOST=rabbitmqServer
    networks:
      - rabbit-network
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmqServer
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge
